### ISSUE TITLE
Is this CPU bound process?

### ISSUE THREAD

**Issue by rikabi89** [alexlnkp/Easy-Audio-Diarisation#1]
Thanks first of all for your efforts. 

I've got this running. But am just wondering is this purely a CPU based effort/process as my GPU is not being utilised. Am wondering if am having a cuda malfunction etc

**Comment by alexlnkp** [comment]
> Thanks first of all for your efforts.
> 
> I've got this running. But am just wondering is this purely a CPU based effort/process as my GPU is not being utilised. Am wondering if am having a cuda malfunction etc

Currently it is CPU only, however in future I'm planning on adding CUDA support. Thanks for reporting this! :)
